# Generated by Django 2.2.7 on 2019-11-21 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0003_auto_20181108_0011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=30)),
                ('compania', models.CharField(default='', max_length=30)),
                ('anio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('anio', models.IntegerField()),
                ('consola', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='mains',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.Menu'),
        ),
        migrations.AlterField(
            model_name='mains',
            name='personaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torneo.Cliente'),
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
        migrations.DeleteModel(
            name='Personaje',
        ),
        migrations.AddField(
            model_name='menu',
            name='personajes',
            field=models.ManyToManyField(through='torneo.Mains', to='torneo.Cliente'),
        ),
    ]
