# Generated by Django 2.2.7 on 2019-11-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0004_auto_20191121_0428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='compania',
        ),
    ]
