# Generated by Django 2.2.7 on 2019-11-21 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneo', '0005_remove_cliente_compania'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='consola',
        ),
    ]
